version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uesr_api_application
    ports:
      - "5000:80"
    depends_on:
      - db
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - ./Script:/docker-entrypoint-initdb.d